import type { TProduct } from "../types/product";

export const products = [
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-1.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "SOL-001",
    path: "sol",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-2.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "LUNA-001",
    path: "luna",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-3.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "EST-001",
    path: "estrella",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-4.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "NUB-001",
    path: "nube",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-5.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "ARC-001",
    path: "arcoiris",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-6.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "CIE-001",
    path: "cielo",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-7.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "PAR-002",
    path: "paramo",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-8.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "AST-001",
    path: "astronauta",
  },
  {
    name: "Pack x3 Panties para Niña",
    src: "/img-9.jpeg",
    price: 15000,
    priceOld: 30000,
    reference: "GAL-001",
    path: "galaxia",
  },
] as TProduct[];
